### ISSUE TITLE
second instance

### ISSUE THREAD

**Issue by chheiss** [CyberDNS/Lupusec2Mqtt#20]
Hi! Are you planning on adding the possibility to add a second alarm system? 

One is working fine, a secondary home with another lupusec would be nice.

That would be great!

**Comment by CyberDNS** [comment]
Hi,

I analyzed the current architecture of the code, and decided for the moment to not provide this functionality because of complexness of changes needed.

Probably this work around could help, mainly it tries to add two instances of the same addon:
https://community.home-assistant.io/t/deploy-two-of-more-zigbee2mqtt-on-one-hassio-instance/206311/6

Regards,
David
