### ISSUE TITLE
Lupusec2Mqtt Mosquito Problem

### ISSUE THREAD

**Issue by Airbrando** [CyberDNS/Lupusec2Mqtt#32]
Hi,
Everything works fine till the Update from the Mosquitto Broker 6.0.2
When i update to this version from my 6.0.1 the Lupusec2Mqtt isnt working anymore. Can someone help me ?

**Comment by CyberDNS** [comment]
Hi, 
Did you already try to restart Lupusec2Mqtt after upgrading to Mosquitto 6.0.2?
Or do you get some kind of error message?
Best regards,
David

**Comment by Airbrando** [comment]
Yes i restartet the whole Homeassistant but its not working anymore i got in the lupusec2mqtt addon no error messages. But in the mosquitto addon there is in the log there is this message :

Socket error on client <unknown>, disconnecting.

**Comment by CyberDNS** [comment]
Ok, I think restarting Homeassistant is not helping because it is running in another container, all the different addons are running in separate containers. So you have to restart the Lupusec2Mqtt addon.

![image](https://user-images.githubusercontent.com/34795406/166155461-6a53a0e3-f0c3-481f-a99a-1664f1031196.png)

**Comment by Airbrando** [comment]
But iam running Homeassistant not in an container. Iam running it on an rasperry with supervisor. There is no container like docker or ?

**Comment by CyberDNS** [comment]
Ok, in that case you should see a container with lupusec2mqtt in the name when you do a docker ps.
Then with the container id or name do a docker restart of the lupusec2mqtt container.

**Comment by Airbrando** [comment]
Mhh i dont understand it. You say restart container. I have no container. I installed the lupusec2mqtt via supervisor

**Comment by CyberDNS** [comment]
Ok, so you installed it from the menu point Configuration > Addons, Backup and Supervisor? In that case you have to click on Lupusec2Mqqt card and then you will arrive in the view from where I took the screenshot above. Then click restart.

**Comment by Airbrando** [comment]
Yes. Thats awesome. Now it works. Why do i habe to restart it manually and not with a restart from Homeassistant? But now it works. Thank you very much

**Comment by CyberDNS** [comment]
Glad to hear that it is working now 🙂.

The reason is that all the add-ons run in their own docker container. And homeassistant is also running in one docker container, so mainly if you restart homeassistant only that  container is restarted and the add-ons are continuing running.
Another possibility would have been to restart the raspberry pi by a sudo shutdown - r now. That would restart all the add-ons.
In a future version I will implement that Lupusec2Mqtt will automatically reconnect after the connection is lost with MQTT.

Best regard,
David

**Comment by Airbrando** [comment]
Ah now i understand what you mean with the restart and the own container. I will mention that when i have another problem ;-) thanks again for your support.

**Comment by CyberDNS** [comment]
No problem, you are welcome. 🙂

I will close the issue.
